name: Mirror to Account B

on:
  push:
    branches: ['**']
    tags: ['**']
  delete:
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        run: |
          git clone --mirror \
            "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" \
            repo.git
          cd repo.git
          git push --mirror \
            "https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/markoprljic/${{ github.event.repository.name }}.git"
